// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN3RTt3PdVAPW3xA2l0s47LVjtiVPBNfE',
    appId: '1:501652481080:web:7c83416b5bae2c63b972cd',
    messagingSenderId: '501652481080',
    projectId: 'fire-response-app-cfab4',
    authDomain: 'fire-response-app-cfab4.firebaseapp.com',
    storageBucket: 'fire-response-app-cfab4.firebasestorage.app',
    measurementId: 'G-NG1TKTLKSS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOu339jzrRas7ahCtcA3Pe5VRKUzh2YYo',
    appId: '1:501652481080:android:ef215ff37df75454b972cd',
    messagingSenderId: '501652481080',
    projectId: 'fire-response-app-cfab4',
    storageBucket: 'fire-response-app-cfab4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF-aLpvHlDYB0kdhvC3_JJS4RJQ1LhAqQ',
    appId: '1:501652481080:ios:553e998a9a62e800b972cd',
    messagingSenderId: '501652481080',
    projectId: 'fire-response-app-cfab4',
    storageBucket: 'fire-response-app-cfab4.firebasestorage.app',
    iosClientId: '501652481080-vv85ekjgr3cck08e12un69fdss8vjopt.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireResponseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBF-aLpvHlDYB0kdhvC3_JJS4RJQ1LhAqQ',
    appId: '1:501652481080:ios:553e998a9a62e800b972cd',
    messagingSenderId: '501652481080',
    projectId: 'fire-response-app-cfab4',
    storageBucket: 'fire-response-app-cfab4.firebasestorage.app',
    iosClientId: '501652481080-vv85ekjgr3cck08e12un69fdss8vjopt.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireResponseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBN3RTt3PdVAPW3xA2l0s47LVjtiVPBNfE',
    appId: '1:501652481080:web:8652d5d7f7f2e376b972cd',
    messagingSenderId: '501652481080',
    projectId: 'fire-response-app-cfab4',
    authDomain: 'fire-response-app-cfab4.firebaseapp.com',
    storageBucket: 'fire-response-app-cfab4.firebasestorage.app',
    measurementId: 'G-EG9V6QWMR2',
  );

}